title:              Vinod's Blog
email:              vinod.rad119@gmail.com
description:        My projects in Machine Learning, Data Science and NLP
author:             Vinod Radhakrishnan
baseurl:            ""
url:                "https://radhakri119.github.io"

# Social Profiles
twitter_username:   calvinhobbes119
github_username:    radhakri119
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
